# Generated by Django 5.2.13 on 2026-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tema',
            field=models.CharField(default='escuro', max_length=10),
        ),
    ]
