# Generated by Django 5.2.13 on 2026-04-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tema',
        ),
    ]
