# Generated by Django 5.2.13 on 2026-04-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
