# Generated by Django 5.2.13 on 2026-06-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_card_data_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='descricao',
            field=models.CharField(blank=True, null=True),
        ),
    ]
