# Generated by Django 5.2.13 on 2026-06-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_card_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
