# Generated by Django 5.2.13 on 2026-07-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_card_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='prioridade',
            field=models.CharField(choices=[('normal', 'Normal'), ('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='responsavel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallpaper',
            field=models.CharField(default='montanha.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
