# Generated by Django 5.2.13 on 2026-06-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_card_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallpaper',
            field=models.CharField(default='montanha.jpg', max_length=100),
        ),
    ]
