# Generated by Django 5.2.13 on 2026-07-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_card_prioridade_card_responsavel_card_tags_and_more'),
        ('accounts', '0009_card_prioridade_card_responsavel_card_tags_and_more'),
    ]

    operations = [
    ]
